Develop
j7programador/placetogrow pull request #5
Opened 2024-06-30 21:26 UTC by j7programador

Stage 1 Bootcamp

2024-06-30 21:29 UTC, j7programador commented
@barbosa89

2024-07-05 21:00 UTC, barbosa89 requested changes

2024-07-05 21:00 UTC, barbosa89 commented on .env
> +APP_ENV=local
Ignorar archivo

2024-07-05 21:00 UTC, barbosa89 commented on app/Actions/MicroSites/DeleteAction.php
> +        MicroSite::destroy($id);
No necesario para acciones simples

2024-07-05 21:00 UTC, barbosa89 commented on app/Constants/CategoriesEnum.php
> +    case MARKETERS = 'Marketers';
Las categorías deben ser creadas mediante CRUD

2024-07-05 21:00 UTC, barbosa89 commented on app/Constants/CategoriesEnum.php
> +
Eliminar líneas en blanco

2024-07-05 21:00 UTC, barbosa89 commented on app/Constants/CurrencyEnum.php
> +enum CurrencyEnum
Quita el sufijo Enum

2024-07-05 21:00 UTC, barbosa89 commented on app/Constants/Permissions.php
> +
Eliminar espacios en blanco

2024-07-05 21:00 UTC, barbosa89 commented on app/Constants/Permissions.php
> +    public const  MICROSITE_VIEW = 'microsite_view';
Usar enum

2024-07-05 21:00 UTC, barbosa89 commented on database/seeders/DatabaseSeeder.php
> -            'name' => 'Tes User',
Recomendacion:

Comando de instalación -> app:install
 Comando de creación de usuarios

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +    public function index(): \Inertia\Response
Importa el namespace

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +            'microsites' => MicroSite::all(),
Implementar paginación

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +            'canDelete' => auth()->user()->can(Permissions::MICROSITE_DELETE),
Implementar view-models

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +        $validated = $request->validate([
Usar form-requests

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +        return to_route('microsites.index')->with('success', 'Microsite created successfully.');
Implementar multi-lenguaje i18n: laravel vue3-i18n

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +            'type_microsite' => 'required',
Agregar moneda y tiempo de expiración

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +            'documentTypes' => array_column(DocumentTypeEnum::cases(), 'name'),
Implementar trait con método toArray

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +        $microsite = MicroSite::query()->where('slug', $slug)->first();
Separar controladores por rol

Admin/MicroSiteController
Customer/MicroSiteController
MicroSiteController

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +        if($micrositeType == 'BASIC'){
Implementar patrón estrategia en una clase que maneje la lógica por sitio

2024-07-05 21:00 UTC, barbosa89 commented on routes/web.php
> +Route::get('/microsites/create', [\App\Http\Controllers\MicroSiteController::class, 'create'])
Recomendación de rutas:

Separar rutas admin -> admin.php
Crear un grupo con prefijo de ruta admin y prefijo de nombre -> /admin/microsites -> admin.microsites.index

2024-07-05 21:00 UTC, barbosa89 commented on routes/web.php
> +Route::get('/microsites', [\App\Http\Controllers\MicroSiteController::class, 'index'])
Importa los namespace

2024-07-05 21:00 UTC, barbosa89 commented on database/migrations/2024_06_13_204623_create_categories_table.php
> -            $table->id();
Columnas de categorías: name y slug, el slug se puede generar con Eloquent Sluggable

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +        $microSite = MicroSite::query()->where('id', $id)->first();
Selecciones los campos requeridos

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/UserController.php
> +        return to_route('users.index')->with('success', 'User deleted');
Agregar línea en blanco antes de cada return

2024-07-05 21:00 UTC, barbosa89 commented on .github/workflows/laravel.yml
> +     - feature/cicd
Reemplazar por master

2024-07-05 21:00 UTC, barbosa89 commented on .github/workflows/laravel.yml
> +      - name: Run npm
Podrías subir los assets compilados

2024-07-05 21:00 UTC, barbosa89 commented on app/Http/Controllers/MicroSiteController.php
> +    public function create() : \Inertia\Response
Aplicar PSR:

Estilo usar Laravel Pint
Leer https://www.php-fig.org/psr/psr-12

2024-07-05 21:00 UTC, barbosa89 commented on .github/workflows/laravel.yml
> +    steps:
Pasos de CI:

1. Analizar estilo con Pint
2. Analizar el código con Larastan
3. Ejecutar los tests

2024-07-05 21:00 UTC, barbosa89 commented on tests/Feature/DeleteActionUser.php
> +class DeleteActionUser extends TestCase
La prueba es unitaria, pero debe ser testeada en los test del controlador de usuarios

2024-07-05 21:00 UTC, barbosa89 commented on tests/Feature/MicroSitesIndexStoreTest.php
> +    public function testFormMicroSites(): void
Organización de pruebas

Feature/Admin/MicroSites/IndexMicroSiteTest: si puede acceder un usuario anónimo, si puede acceder un usuario sin rol o permiso, si puede acceder un usuario con rol o permiso
Feature/Admin/MicroSites/CreateMicroSiteTest
Feature/Admin/MicroSites/StoreMicroSiteTest

Feature/MicroSites/IndexMicroSiteTest
Feature/MicroSites/ShowMicroSiteTest

Unit/Commands/CommandNameTest.php

2024-07-05 21:00 UTC, barbosa89 commented on tests/Feature/MicroSitesIndexStoreTest.php
> +        $user->assignRole('Admin');
Usar constantes

2024-07-14 18:56 UTC, merged